name: Continuous Integration

on:
  pull_request:
    branches:
      - main
      - dev
    types: [opened, reopened, synchronize]

jobs:
  # このジョブ名を設定する
  code-check:
    runs-on: ubuntu-latest
    steps:
      - name: run code check
        run: |
          echo 'format, lint, UT and more'
